version: '3.8'

services:
  deployer:
    container_name: deployer
    image: node:14
    working_dir: /usr/src/client
    command: bash -c "npm install && node main.js deploy"
    volumes:
        - ./client:/usr/src/client
        - ./client/node_modules_cont:/usr/src/client/node_modules   
