version: '3.8'


services:
  tester:
    container_name: tester
    image: node:14
    working_dir: /usr/src/client
    command: bash -c "node main.js increment"
    volumes:
        - ./client:/usr/src/client
        - ./client/node_modules_cont:/usr/src/client/node_modules   

